apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: medflow-real-secrets
  namespace: medflow-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: medflow-real-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        database-url: "postgresql+psycopg://{{ .db_username }}:{{ .db_password }}@{{ .db_host }}:{{ .db_port }}/{{ .db_name }}"
        jwt-secret-key: "{{ .jwt_secret_key }}"
        jwt-algorithm: "{{ .jwt_algorithm }}"
        access-token-expire-minutes: "{{ .access_token_expire_minutes }}"
  data:
    - secretKey: db_username
      remoteRef:
        key: dev/medflow-dev-db/credentials
        property: username
    - secretKey: db_password
      remoteRef:
        key: dev/medflow-dev-db/credentials
        property: password
    - secretKey: db_host
      remoteRef:
        key: dev/medflow-dev-db/credentials
        property: host
    - secretKey: db_port
      remoteRef:
        key: dev/medflow-dev-db/credentials
        property: port
    - secretKey: db_name
      remoteRef:
        key: dev/medflow-dev-db/credentials
        property: dbname
    - secretKey: jwt_secret_key
      remoteRef:
        key: /medflow/dev/app
        property: jwt-secret-key
    - secretKey: jwt_algorithm
      remoteRef:
        key: /medflow/dev/app
        property: jwt-algorithm
    - secretKey: access_token_expire_minutes
      remoteRef:
        key: /medflow/dev/app
        property: access-token-expire-minutes
