server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;

    location / {
        try_files $uri /index.html;
    }

    # API Reverse Proxies for Health Checks
    location /api/auth-service/ {
        proxy_pass http://auth-service:8000/;
        proxy_connect_timeout 2s;
    }
    location /api/patient-service/ {
        proxy_pass http://patient-service:8000/;
        proxy_connect_timeout 2s;
    }
    location /api/appointment-service/ {
        proxy_pass http://appointment-service:8000/;
        proxy_connect_timeout 2s;
    }
    location /api/records-service/ {
        proxy_pass http://records-service:8000/;
        proxy_connect_timeout 2s;
    }
    location /api/pharmacy-service/ {
        proxy_pass http://pharmacy-service:8000/;
        proxy_connect_timeout 2s;
    }
    location /api/billing-service/ {
        proxy_pass http://billing-service:8000/;
        proxy_connect_timeout 2s;
    }
    location /api/notification-service/ {
        proxy_pass http://notification-service:8000/;
        proxy_connect_timeout 2s;
    }
}
