global:
  environment: dev
  imageRegistry: 724476121315.dkr.ecr.us-east-2.amazonaws.com/
services:
  auth:
    enabled: true
    name: auth-service
    image:
      repository: medflow/auth-service
      tag: 75f9993206005128e2ffaec41951bfbf6aa072aa
    port: 8000
    replicas: 1
    env:
      APP_NAME: medflow-auth-service
      LOG_LEVEL: INFO
    secretEnv:
      DATABASE_URL:
        secretName: medflow-real-secrets
        key: database-url
      JWT_SECRET_KEY:
        secretName: medflow-real-secrets
        key: jwt-secret-key
      JWT_ALGORITHM:
        secretName: medflow-real-secrets
        key: jwt-algorithm
      ACCESS_TOKEN_EXPIRE_MINUTES:
        secretName: medflow-real-secrets
        key: access-token-expire-minutes
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  patient:
    enabled: true
    name: patient-service
    image:
      repository: medflow/patient-service
      tag: 75f9993206005128e2ffaec41951bfbf6aa072aa
    port: 8000
    replicas: 1
    env:
      APP_NAME: medflow-patient-service
      LOG_LEVEL: INFO
    secretEnv:
      DATABASE_URL:
        secretName: medflow-real-secrets
        key: database-url
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  appointment:
    enabled: true
    name: appointment-service
    image:
      repository: medflow/appointment-service
      tag: 75f9993206005128e2ffaec41951bfbf6aa072aa
    port: 8000
    replicas: 1
    env:
      APP_NAME: medflow-appointment-service
      LOG_LEVEL: INFO
    secretEnv:
      DATABASE_URL:
        secretName: medflow-real-secrets
        key: database-url
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  records:
    enabled: true
    name: records-service
    image:
      repository: medflow/records-service
      tag: 75f9993206005128e2ffaec41951bfbf6aa072aa
    port: 8000
    replicas: 1
    env:
      APP_NAME: medflow-records-service
      LOG_LEVEL: INFO
    secretEnv:
      DATABASE_URL:
        secretName: medflow-real-secrets
        key: database-url
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  pharmacy:
    enabled: true
    name: pharmacy-service
    image:
      repository: medflow/pharmacy-service
      tag: 75f9993206005128e2ffaec41951bfbf6aa072aa
    port: 8000
    replicas: 1
    env:
      APP_NAME: medflow-pharmacy-service
      LOG_LEVEL: INFO
    secretEnv:
      DATABASE_URL:
        secretName: medflow-real-secrets
        key: database-url
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  billing:
    enabled: true
    name: billing-service
    image:
      repository: medflow/billing-service
      tag: 75f9993206005128e2ffaec41951bfbf6aa072aa
    port: 8000
    replicas: 1
    env:
      APP_NAME: medflow-billing-service
      LOG_LEVEL: INFO
    secretEnv:
      DATABASE_URL:
        secretName: medflow-real-secrets
        key: database-url
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  notification:
    enabled: true
    name: notification-service
    image:
      repository: medflow/notification-service
      tag: 75f9993206005128e2ffaec41951bfbf6aa072aa
    port: 8000
    replicas: 1
    env:
      APP_NAME: medflow-notification-service
      LOG_LEVEL: INFO
    secretEnv:
      DATABASE_URL:
        secretName: medflow-real-secrets
        key: database-url
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  frontend:
    enabled: true
    name: frontend
    type: LoadBalancer
    image:
      repository: medflow/frontend
      tag: d6959c9d03e5f105ac72ae693a63e56a3e473270
    port: 8080
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
